/**
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.virtmodel.validation;

import at.ac.tuwien.big.virtmodel.validation.AbstractVLangValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class VLangValidator extends AbstractVLangValidator {
}
