/*
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.ui;

import at.ac.tuwien.big.simplejava.ui.internal.SimplejavaActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimplejavaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SimplejavaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SimplejavaActivator.getInstance().getInjector(SimplejavaActivator.AT_AC_TUWIEN_BIG_SIMPLEJAVA);
	}
	
}
