/*
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.simpleaspect.parser.antlr;

import at.ac.tuwien.big.simpleaspect.parser.antlr.internal.InternalSimpleAspectParser;
import at.ac.tuwien.big.simpleaspect.services.SimpleAspectGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SimpleAspectParser extends AbstractAntlrParser {

	@Inject
	private SimpleAspectGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSimpleAspectParser createParser(XtextTokenStream stream) {
		return new InternalSimpleAspectParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Aspect";
	}

	public SimpleAspectGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SimpleAspectGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
