<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="router" nsURI="http://router/1.0" nsPrefix="router">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Provider" eSuperTypes="#//Agent">
    <eOperations name="project" lowerBound="1" eType="#//Provider">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="project_rightserv" lowerBound="1" eType="#//Server">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="explode" upperBound="-1" eType="#//SMParamSingle_Provider"/>
    <eOperations name="explode_rightserv" upperBound="-1" eType="#//SMParamSingle_Server"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightserv" lowerBound="1"
        eType="#//Server" eOpposite="#//Server/provider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agent">
    <eOperations name="createParameter" lowerBound="1" eType="#//SMParam">
      <eParameters name="variant" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
      <eParameters name="version" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    </eOperations>
    <eOperations name="project" lowerBound="1" eType="#//Agent">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="project_name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="project_speed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="explode" upperBound="-1" eType="#//SMParamSingle_Agent"/>
    <eOperations name="explode_name" upperBound="-1" eType="#//SMParamSingle_EString"/>
    <eOperations name="explode_speed" upperBound="-1" eType="#//SMParamSingle_EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Consumer" eSuperTypes="#//Agent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="consumerNamesEqual"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="consumerNamesEqual" value="name = rightcomp.name"/>
    </eAnnotations>
    <eOperations name="project" lowerBound="1" eType="#//Consumer">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="project_rightcomp" lowerBound="1" eType="#//Computer">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="explode" upperBound="-1" eType="#//SMParamSingle_Consumer"/>
    <eOperations name="explode_rightcomp" upperBound="-1" eType="#//SMParamSingle_Computer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightcomp" lowerBound="1"
        eType="#//Computer" eOpposite="#//Computer/consumer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device">
    <eOperations name="createParameter" lowerBound="1" eType="#//SMParam">
      <eParameters name="variant" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
      <eParameters name="version" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    </eOperations>
    <eOperations name="project" lowerBound="1" eType="#//Device">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="project_outgoing" upperBound="-1" eType="#//Cable">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="project_incoming" upperBound="-1" eType="#//Cable">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="project_name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="explode" upperBound="-1" eType="#//SMParamSingle_Device"/>
    <eOperations name="explode_outgoing" upperBound="-1" eType="#//SMParamMulti_Cable"/>
    <eOperations name="explode_incoming" upperBound="-1" eType="#//SMParamMulti_Cable"/>
    <eOperations name="explode_name" upperBound="-1" eType="#//SMParamSingle_EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//Cable" containment="true" eOpposite="#//Cable/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//Cable" eOpposite="#//Cable/target"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cable">
    <eOperations name="createParameter" lowerBound="1" eType="#//SMParam">
      <eParameters name="variant" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
      <eParameters name="version" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    </eOperations>
    <eOperations name="project" lowerBound="1" eType="#//Cable">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="project_speed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="project_source" lowerBound="1" eType="#//Device">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="project_target" lowerBound="1" eType="#//Device">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="explode" upperBound="-1" eType="#//SMParamSingle_Cable"/>
    <eOperations name="explode_speed" upperBound="-1" eType="#//SMParamSingle_EBigInteger"/>
    <eOperations name="explode_source" upperBound="-1" eType="#//SMParamSingle_Device"/>
    <eOperations name="explode_target" upperBound="-1" eType="#//SMParamSingle_Device"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Device" eOpposite="#//Device/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Device" eOpposite="#//Device/incoming"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Server" eSuperTypes="#//Device">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="serverNoIncoming"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="serverNoIncoming" value="incoming->isEmpty()"/>
    </eAnnotations>
    <eOperations name="project" lowerBound="1" eType="#//Server">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="project_provider" eType="#//Provider">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="explode" upperBound="-1" eType="#//SMParamSingle_Server"/>
    <eOperations name="explode_provider" upperBound="-1" eType="#//SMParamSingle_Provider"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provider" eType="#//Provider"
        eOpposite="#//Provider/rightserv"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Computer" eSuperTypes="#//Device">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="computerNoOutgoing"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="computerNoOutgoing" value="outgoing->isEmpty()"/>
    </eAnnotations>
    <eOperations name="project" lowerBound="1" eType="#//Computer">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="project_consumer" lowerBound="1" eType="#//Consumer">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="explode" upperBound="-1" eType="#//SMParamSingle_Computer"/>
    <eOperations name="explode_consumer" upperBound="-1" eType="#//SMParamSingle_Consumer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consumer" lowerBound="1"
        eType="#//Consumer" eOpposite="#//Consumer/rightcomp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Router" eSuperTypes="#//Device">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="routerHandlesSpeed"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="routerHandlesSpeed" value="outgoing.speed->sum() &lt;= incoming.speed->sum()"/>
    </eAnnotations>
    <eOperations name="myOp" unique="false" upperBound="-1">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
      <eParameters name="param" ordered="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/OCL/Collection">
          <details key="nullFree" value="false"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="project" lowerBound="1" eType="#//Router">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="project_maxSpeed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="explode" upperBound="-1" eType="#//SMParamSingle_Router"/>
    <eOperations name="explode_maxSpeed" upperBound="-1" eType="#//SMParamSingle_EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxSpeed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CopperCable" eSuperTypes="#//Cable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="losSpeed"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="losSpeed" value="speed &lt;= 4"/>
    </eAnnotations>
    <eOperations name="project" lowerBound="1" eType="#//CopperCable">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="explode" upperBound="-1" eType="#//SMParamSingle_CopperCable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlassFiberCable" eSuperTypes="#//Cable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="highSpeed"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="highSpeed" value="speed >= 4"/>
    </eAnnotations>
    <eOperations name="project" lowerBound="1" eType="#//GlassFiberCable">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="explode" upperBound="-1" eType="#//SMParamSingle_GlassFiberCable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eOperations name="createParameter" lowerBound="1" eType="#//SMParam">
      <eParameters name="variant" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
      <eParameters name="version" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    </eOperations>
    <eOperations name="project" lowerBound="1" eType="#//Container">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="project_agents" upperBound="-1" eType="#//Agent">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="project_devices" upperBound="-1" eType="#//Device">
      <eParameters name="pars" upperBound="-1" eType="#//SMParam"/>
    </eOperations>
    <eOperations name="explode" upperBound="-1" eType="#//SMParamSingle_Container"/>
    <eOperations name="explode_agents" upperBound="-1" eType="#//SMParamMulti_Agent"/>
    <eOperations name="explode_devices" upperBound="-1" eType="#//SMParamMulti_Device"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agents" upperBound="-1"
        eType="#//Agent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devices" upperBound="-1"
        eType="#//Device" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variant" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamSingle_Server" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Server"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamMulti_Server" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//Server"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamSingle_Computer" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Computer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamMulti_Computer" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//Computer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamSingle_Router" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Router"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamMulti_Router" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//Router"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamSingle_GlassFiberCable" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//GlassFiberCable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamMulti_GlassFiberCable" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//GlassFiberCable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamSingle_Container" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamMulti_Container" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//Container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamSingle_Provider" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Provider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamMulti_Provider" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//Provider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamSingle_CopperCable" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//CopperCable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamMulti_CopperCable" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//CopperCable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamSingle_EBigInteger" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamMulti_EBigInteger" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamSingle_Agent" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Agent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamMulti_Agent" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//Agent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamSingle_Consumer" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Consumer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamMulti_Consumer" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//Consumer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamSingle_EString" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamMulti_EString" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamSingle_Cable" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Cable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamMulti_Cable" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//Cable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamSingle_Device" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Device"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMParamMulti_Device" eSuperTypes="#//SMParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//Device"/>
  </eClassifiers>
</ecore:EPackage>
