/**
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.virtmodel;

import at.ac.tuwien.big.virtmodel.VLangStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class VLangStandaloneSetup extends VLangStandaloneSetupGenerated {
  public static void doSetup() {
    new VLangStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
