/*
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.school;

import java.io.ByteArrayOutputStream;
import java.net.URL;
import java.io.IOException;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import java.io.InputStream;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SchoolTextRuntimeModule extends AbstractSchoolTextRuntimeModule {
	

	public static byte[] getBytes(String name) throws IOException {
		Bundle bundle = FrameworkUtil.getBundle(SchoolTextRuntimeModule.class);
		URL url = bundle.getEntry(name); 
		InputStream is = url.openStream();
		ByteArrayOutputStream baos = new ByteArrayOutputStream();
		try { 
		  is = url.openStream ();
		  byte[] byteChunk = new byte[4096]; // Or whatever size you want to read in at a time.
		  int n;

		  while ( (n = is.read(byteChunk)) > 0 ) {
		    baos.write(byteChunk, 0, n);
		  }
		}
		catch (IOException e) {e.printStackTrace();}
		return baos.toByteArray();
	}
	
	
}
