/**
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.simpleaspect.simpleAspect;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pointcut Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.ac.tuwien.big.simpleaspect.simpleAspect.PointcutRef#getPointcut <em>Pointcut</em>}</li>
 *   <li>{@link at.ac.tuwien.big.simpleaspect.simpleAspect.PointcutRef#getParameterValue <em>Parameter Value</em>}</li>
 * </ul>
 *
 * @see at.ac.tuwien.big.simpleaspect.simpleAspect.SimpleAspectPackage#getPointcutRef()
 * @model
 * @generated
 */
public interface PointcutRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Pointcut</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pointcut</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pointcut</em>' reference.
   * @see #setPointcut(Pointcut)
   * @see at.ac.tuwien.big.simpleaspect.simpleAspect.SimpleAspectPackage#getPointcutRef_Pointcut()
   * @model
   * @generated
   */
  Pointcut getPointcut();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.simpleaspect.simpleAspect.PointcutRef#getPointcut <em>Pointcut</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pointcut</em>' reference.
   * @see #getPointcut()
   * @generated
   */
  void setPointcut(Pointcut value);

  /**
   * Returns the value of the '<em><b>Parameter Value</b></em>' containment reference list.
   * The list contents are of type {@link at.ac.tuwien.big.simpleaspect.simpleAspect.VariableExpression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameter Value</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter Value</em>' containment reference list.
   * @see at.ac.tuwien.big.simpleaspect.simpleAspect.SimpleAspectPackage#getPointcutRef_ParameterValue()
   * @model containment="true"
   * @generated
   */
  EList<VariableExpression> getParameterValue();

} // PointcutRef
