/**
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.simpleaspect.simpleAspect;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unary Pointcut Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.ac.tuwien.big.simpleaspect.simpleAspect.UnaryPointcutCondition#getCondition <em>Condition</em>}</li>
 * </ul>
 *
 * @see at.ac.tuwien.big.simpleaspect.simpleAspect.SimpleAspectPackage#getUnaryPointcutCondition()
 * @model
 * @generated
 */
public interface UnaryPointcutCondition extends PointcutCondition
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(PointcutCondition)
   * @see at.ac.tuwien.big.simpleaspect.simpleAspect.SimpleAspectPackage#getUnaryPointcutCondition_Condition()
   * @model containment="true"
   * @generated
   */
  PointcutCondition getCondition();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.simpleaspect.simpleAspect.UnaryPointcutCondition#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(PointcutCondition value);

} // UnaryPointcutCondition
