/*
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.multimodeldesc.ui.tests;

import at.ac.tuwien.big.multimodeldesc.ui.internal.MultimodeldescActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MMDescUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MultimodeldescActivator.getInstance().getInjector("at.ac.tuwien.big.multimodeldesc.MMDesc");
	}

}
