/**
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.virtmodel.tests;

import at.ac.tuwien.big.virtmodel.tests.VLangInjectorProvider;
import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(VLangInjectorProvider.class)
@SuppressWarnings("all")
public class VLangParsingTest {
  @Inject
  private /* ParseHelper<File> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field VLangParsingTest.parseHelper refers to the missing type File"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
