/**
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.simplejava;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.ac.tuwien.big.simplejava.IfStatement#getCondition <em>Condition</em>}</li>
 *   <li>{@link at.ac.tuwien.big.simplejava.IfStatement#getThen <em>Then</em>}</li>
 *   <li>{@link at.ac.tuwien.big.simplejava.IfStatement#getElse <em>Else</em>}</li>
 * </ul>
 *
 * @see at.ac.tuwien.big.simplejava.SimplejavaPackage#getIfStatement()
 * @model
 * @generated
 */
public interface IfStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(ParanthesisOrBinaryExpression)
   * @see at.ac.tuwien.big.simplejava.SimplejavaPackage#getIfStatement_Condition()
   * @model containment="true"
   * @generated
   */
  ParanthesisOrBinaryExpression getCondition();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.simplejava.IfStatement#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(ParanthesisOrBinaryExpression value);

  /**
   * Returns the value of the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Then</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' containment reference.
   * @see #setThen(MethodBlock)
   * @see at.ac.tuwien.big.simplejava.SimplejavaPackage#getIfStatement_Then()
   * @model containment="true"
   * @generated
   */
  MethodBlock getThen();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.simplejava.IfStatement#getThen <em>Then</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then</em>' containment reference.
   * @see #getThen()
   * @generated
   */
  void setThen(MethodBlock value);

  /**
   * Returns the value of the '<em><b>Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Else</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else</em>' containment reference.
   * @see #setElse(MethodBlock)
   * @see at.ac.tuwien.big.simplejava.SimplejavaPackage#getIfStatement_Else()
   * @model containment="true"
   * @generated
   */
  MethodBlock getElse();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.simplejava.IfStatement#getElse <em>Else</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else</em>' containment reference.
   * @see #getElse()
   * @generated
   */
  void setElse(MethodBlock value);

} // IfStatement
