/**
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.simplejava;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see at.ac.tuwien.big.simplejava.SimplejavaPackage#getSimpleStatement()
 * @model
 * @generated
 */
public interface SimpleStatement extends EObject
{
} // SimpleStatement
