/**
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.simplejava.impl;

import at.ac.tuwien.big.simplejava.SimpleVariableDeclaration;
import at.ac.tuwien.big.simplejava.SimplejavaPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Simple Variable Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SimpleVariableDeclarationImpl extends SimpleStatementImpl implements SimpleVariableDeclaration
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimpleVariableDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SimplejavaPackage.Literals.SIMPLE_VARIABLE_DECLARATION;
  }

} //SimpleVariableDeclarationImpl
