/**
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.virtmodel.scoping;

import at.ac.tuwien.big.virtmodel.scoping.AbstractVLangScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class VLangScopeProvider extends AbstractVLangScopeProvider {
}
