/*
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.simpleaspect


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SimpleAspectStandaloneSetup extends SimpleAspectStandaloneSetupGenerated {

	def static void doSetup() {
		new SimpleAspectStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
