/*
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.multimodeldesc.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMMDescValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(at.ac.tuwien.big.multimodeldesc.mMDesc.MMDescPackage.eINSTANCE);
		return result;
	}
	
}
