/**
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.ide;

import at.ac.tuwien.big.SimplejavaRuntimeModule;
import at.ac.tuwien.big.SimplejavaStandaloneSetup;
import at.ac.tuwien.big.ide.SimplejavaIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SimplejavaIdeSetup extends SimplejavaStandaloneSetup {
  @Override
  public Injector createInjector() {
    SimplejavaRuntimeModule _simplejavaRuntimeModule = new SimplejavaRuntimeModule();
    SimplejavaIdeModule _simplejavaIdeModule = new SimplejavaIdeModule();
    return Guice.createInjector(Modules2.mixin(_simplejavaRuntimeModule, _simplejavaIdeModule));
  }
}
