/**
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.virtmodel.vLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Calculated Value</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see at.ac.tuwien.big.virtmodel.vLang.VLangPackage#getCalculatedValue()
 * @model
 * @generated
 */
public interface CalculatedValue extends SingleValue
{
} // CalculatedValue
