/**
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.virtmodel.vLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For Loop Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.ac.tuwien.big.virtmodel.vLang.ForLoopStatement#getName <em>Name</em>}</li>
 *   <li>{@link at.ac.tuwien.big.virtmodel.vLang.ForLoopStatement#getValue <em>Value</em>}</li>
 *   <li>{@link at.ac.tuwien.big.virtmodel.vLang.ForLoopStatement#getLoopExpr <em>Loop Expr</em>}</li>
 * </ul>
 *
 * @see at.ac.tuwien.big.virtmodel.vLang.VLangPackage#getForLoopStatement()
 * @model
 * @generated
 */
public interface ForLoopStatement extends SingleStatement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see at.ac.tuwien.big.virtmodel.vLang.VLangPackage#getForLoopStatement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.virtmodel.vLang.ForLoopStatement#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(FunctionAssignment)
   * @see at.ac.tuwien.big.virtmodel.vLang.VLangPackage#getForLoopStatement_Value()
   * @model containment="true"
   * @generated
   */
  FunctionAssignment getValue();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.virtmodel.vLang.ForLoopStatement#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(FunctionAssignment value);

  /**
   * Returns the value of the '<em><b>Loop Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Loop Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loop Expr</em>' containment reference.
   * @see #setLoopExpr(SingleStatement)
   * @see at.ac.tuwien.big.virtmodel.vLang.VLangPackage#getForLoopStatement_LoopExpr()
   * @model containment="true"
   * @generated
   */
  SingleStatement getLoopExpr();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.virtmodel.vLang.ForLoopStatement#getLoopExpr <em>Loop Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Loop Expr</em>' containment reference.
   * @see #getLoopExpr()
   * @generated
   */
  void setLoopExpr(SingleStatement value);

} // ForLoopStatement
