/**
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.virtmodel.vLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see at.ac.tuwien.big.virtmodel.vLang.VLangPackage#getFunctionAssignment()
 * @model
 * @generated
 */
public interface FunctionAssignment extends Filter
{
} // FunctionAssignment
