/**
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.virtmodel.vLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Par</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see at.ac.tuwien.big.virtmodel.vLang.VLangPackage#getFunctionPar()
 * @model
 * @generated
 */
public interface FunctionPar extends EObject
{
} // FunctionPar
