/**
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.virtmodel.vLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Java Function Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.ac.tuwien.big.virtmodel.vLang.JavaFunctionDef#getType <em>Type</em>}</li>
 *   <li>{@link at.ac.tuwien.big.virtmodel.vLang.JavaFunctionDef#getName <em>Name</em>}</li>
 *   <li>{@link at.ac.tuwien.big.virtmodel.vLang.JavaFunctionDef#getJavaFunc <em>Java Func</em>}</li>
 * </ul>
 *
 * @see at.ac.tuwien.big.virtmodel.vLang.VLangPackage#getJavaFunctionDef()
 * @model
 * @generated
 */
public interface JavaFunctionDef extends AssignStatement
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link at.ac.tuwien.big.virtmodel.vLang.JavaFunctionType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see at.ac.tuwien.big.virtmodel.vLang.JavaFunctionType
   * @see #setType(JavaFunctionType)
   * @see at.ac.tuwien.big.virtmodel.vLang.VLangPackage#getJavaFunctionDef_Type()
   * @model
   * @generated
   */
  JavaFunctionType getType();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.virtmodel.vLang.JavaFunctionDef#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see at.ac.tuwien.big.virtmodel.vLang.JavaFunctionType
   * @see #getType()
   * @generated
   */
  void setType(JavaFunctionType value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see at.ac.tuwien.big.virtmodel.vLang.VLangPackage#getJavaFunctionDef_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.virtmodel.vLang.JavaFunctionDef#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Java Func</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Java Func</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Java Func</em>' attribute.
   * @see #setJavaFunc(String)
   * @see at.ac.tuwien.big.virtmodel.vLang.VLangPackage#getJavaFunctionDef_JavaFunc()
   * @model
   * @generated
   */
  String getJavaFunc();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.virtmodel.vLang.JavaFunctionDef#getJavaFunc <em>Java Func</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Java Func</em>' attribute.
   * @see #getJavaFunc()
   * @generated
   */
  void setJavaFunc(String value);

} // JavaFunctionDef
