/**
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.virtmodel.vLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ocl Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.ac.tuwien.big.virtmodel.vLang.OclFunction#getOclFunc <em>Ocl Func</em>}</li>
 * </ul>
 *
 * @see at.ac.tuwien.big.virtmodel.vLang.VLangPackage#getOclFunction()
 * @model
 * @generated
 */
public interface OclFunction extends Expression
{
  /**
   * Returns the value of the '<em><b>Ocl Func</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ocl Func</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ocl Func</em>' attribute.
   * @see #setOclFunc(String)
   * @see at.ac.tuwien.big.virtmodel.vLang.VLangPackage#getOclFunction_OclFunc()
   * @model
   * @generated
   */
  String getOclFunc();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.virtmodel.vLang.OclFunction#getOclFunc <em>Ocl Func</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ocl Func</em>' attribute.
   * @see #getOclFunc()
   * @generated
   */
  void setOclFunc(String value);

} // OclFunction
