/**
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.virtmodel.vLang.impl;

import at.ac.tuwien.big.virtmodel.vLang.CalculatedValue;
import at.ac.tuwien.big.virtmodel.vLang.VLangPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Calculated Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CalculatedValueImpl extends SingleValueImpl implements CalculatedValue
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CalculatedValueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VLangPackage.Literals.CALCULATED_VALUE;
  }

} //CalculatedValueImpl
