/**
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.virtmodel.vLang.impl;

import at.ac.tuwien.big.virtmodel.vLang.ForLoopStatement;
import at.ac.tuwien.big.virtmodel.vLang.FunctionAssignment;
import at.ac.tuwien.big.virtmodel.vLang.SingleStatement;
import at.ac.tuwien.big.virtmodel.vLang.VLangPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>For Loop Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link at.ac.tuwien.big.virtmodel.vLang.impl.ForLoopStatementImpl#getName <em>Name</em>}</li>
 *   <li>{@link at.ac.tuwien.big.virtmodel.vLang.impl.ForLoopStatementImpl#getValue <em>Value</em>}</li>
 *   <li>{@link at.ac.tuwien.big.virtmodel.vLang.impl.ForLoopStatementImpl#getLoopExpr <em>Loop Expr</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ForLoopStatementImpl extends SingleStatementImpl implements ForLoopStatement
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected FunctionAssignment value;

  /**
   * The cached value of the '{@link #getLoopExpr() <em>Loop Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoopExpr()
   * @generated
   * @ordered
   */
  protected SingleStatement loopExpr;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ForLoopStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VLangPackage.Literals.FOR_LOOP_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VLangPackage.FOR_LOOP_STATEMENT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FunctionAssignment getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetValue(FunctionAssignment newValue, NotificationChain msgs)
  {
    FunctionAssignment oldValue = value;
    value = newValue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, VLangPackage.FOR_LOOP_STATEMENT__VALUE, oldValue, newValue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue(FunctionAssignment newValue)
  {
    if (newValue != value)
    {
      NotificationChain msgs = null;
      if (value != null)
        msgs = ((InternalEObject)value).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - VLangPackage.FOR_LOOP_STATEMENT__VALUE, null, msgs);
      if (newValue != null)
        msgs = ((InternalEObject)newValue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - VLangPackage.FOR_LOOP_STATEMENT__VALUE, null, msgs);
      msgs = basicSetValue(newValue, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VLangPackage.FOR_LOOP_STATEMENT__VALUE, newValue, newValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SingleStatement getLoopExpr()
  {
    return loopExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLoopExpr(SingleStatement newLoopExpr, NotificationChain msgs)
  {
    SingleStatement oldLoopExpr = loopExpr;
    loopExpr = newLoopExpr;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, VLangPackage.FOR_LOOP_STATEMENT__LOOP_EXPR, oldLoopExpr, newLoopExpr);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLoopExpr(SingleStatement newLoopExpr)
  {
    if (newLoopExpr != loopExpr)
    {
      NotificationChain msgs = null;
      if (loopExpr != null)
        msgs = ((InternalEObject)loopExpr).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - VLangPackage.FOR_LOOP_STATEMENT__LOOP_EXPR, null, msgs);
      if (newLoopExpr != null)
        msgs = ((InternalEObject)newLoopExpr).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - VLangPackage.FOR_LOOP_STATEMENT__LOOP_EXPR, null, msgs);
      msgs = basicSetLoopExpr(newLoopExpr, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VLangPackage.FOR_LOOP_STATEMENT__LOOP_EXPR, newLoopExpr, newLoopExpr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case VLangPackage.FOR_LOOP_STATEMENT__VALUE:
        return basicSetValue(null, msgs);
      case VLangPackage.FOR_LOOP_STATEMENT__LOOP_EXPR:
        return basicSetLoopExpr(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VLangPackage.FOR_LOOP_STATEMENT__NAME:
        return getName();
      case VLangPackage.FOR_LOOP_STATEMENT__VALUE:
        return getValue();
      case VLangPackage.FOR_LOOP_STATEMENT__LOOP_EXPR:
        return getLoopExpr();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VLangPackage.FOR_LOOP_STATEMENT__NAME:
        setName((String)newValue);
        return;
      case VLangPackage.FOR_LOOP_STATEMENT__VALUE:
        setValue((FunctionAssignment)newValue);
        return;
      case VLangPackage.FOR_LOOP_STATEMENT__LOOP_EXPR:
        setLoopExpr((SingleStatement)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VLangPackage.FOR_LOOP_STATEMENT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case VLangPackage.FOR_LOOP_STATEMENT__VALUE:
        setValue((FunctionAssignment)null);
        return;
      case VLangPackage.FOR_LOOP_STATEMENT__LOOP_EXPR:
        setLoopExpr((SingleStatement)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VLangPackage.FOR_LOOP_STATEMENT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case VLangPackage.FOR_LOOP_STATEMENT__VALUE:
        return value != null;
      case VLangPackage.FOR_LOOP_STATEMENT__LOOP_EXPR:
        return loopExpr != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ForLoopStatementImpl
