/**
 * generated by Xtext 2.11.0
 */
package at.ac.tuwien.big.virtmodel.vLang.impl;

import at.ac.tuwien.big.virtmodel.vLang.JavaFunctionDef;
import at.ac.tuwien.big.virtmodel.vLang.JavaFunctionType;
import at.ac.tuwien.big.virtmodel.vLang.VLangPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Java Function Def</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link at.ac.tuwien.big.virtmodel.vLang.impl.JavaFunctionDefImpl#getType <em>Type</em>}</li>
 *   <li>{@link at.ac.tuwien.big.virtmodel.vLang.impl.JavaFunctionDefImpl#getName <em>Name</em>}</li>
 *   <li>{@link at.ac.tuwien.big.virtmodel.vLang.impl.JavaFunctionDefImpl#getJavaFunc <em>Java Func</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JavaFunctionDefImpl extends AssignStatementImpl implements JavaFunctionDef
{
  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final JavaFunctionType TYPE_EDEFAULT = JavaFunctionType.FUNCCALL;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected JavaFunctionType type = TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getJavaFunc() <em>Java Func</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJavaFunc()
   * @generated
   * @ordered
   */
  protected static final String JAVA_FUNC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getJavaFunc() <em>Java Func</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJavaFunc()
   * @generated
   * @ordered
   */
  protected String javaFunc = JAVA_FUNC_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JavaFunctionDefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VLangPackage.Literals.JAVA_FUNCTION_DEF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public JavaFunctionType getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setType(JavaFunctionType newType)
  {
    JavaFunctionType oldType = type;
    type = newType == null ? TYPE_EDEFAULT : newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VLangPackage.JAVA_FUNCTION_DEF__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VLangPackage.JAVA_FUNCTION_DEF__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getJavaFunc()
  {
    return javaFunc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setJavaFunc(String newJavaFunc)
  {
    String oldJavaFunc = javaFunc;
    javaFunc = newJavaFunc;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VLangPackage.JAVA_FUNCTION_DEF__JAVA_FUNC, oldJavaFunc, javaFunc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VLangPackage.JAVA_FUNCTION_DEF__TYPE:
        return getType();
      case VLangPackage.JAVA_FUNCTION_DEF__NAME:
        return getName();
      case VLangPackage.JAVA_FUNCTION_DEF__JAVA_FUNC:
        return getJavaFunc();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VLangPackage.JAVA_FUNCTION_DEF__TYPE:
        setType((JavaFunctionType)newValue);
        return;
      case VLangPackage.JAVA_FUNCTION_DEF__NAME:
        setName((String)newValue);
        return;
      case VLangPackage.JAVA_FUNCTION_DEF__JAVA_FUNC:
        setJavaFunc((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VLangPackage.JAVA_FUNCTION_DEF__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case VLangPackage.JAVA_FUNCTION_DEF__NAME:
        setName(NAME_EDEFAULT);
        return;
      case VLangPackage.JAVA_FUNCTION_DEF__JAVA_FUNC:
        setJavaFunc(JAVA_FUNC_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VLangPackage.JAVA_FUNCTION_DEF__TYPE:
        return type != TYPE_EDEFAULT;
      case VLangPackage.JAVA_FUNCTION_DEF__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case VLangPackage.JAVA_FUNCTION_DEF__JAVA_FUNC:
        return JAVA_FUNC_EDEFAULT == null ? javaFunc != null : !JAVA_FUNC_EDEFAULT.equals(javaFunc);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (type: ");
    result.append(type);
    result.append(", name: ");
    result.append(name);
    result.append(", javaFunc: ");
    result.append(javaFunc);
    result.append(')');
    return result.toString();
  }

} //JavaFunctionDefImpl
